name: ascii workflow
on: push
jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: install cowsay
          run: sudo apt-get install cowsay -y
        
        - name: Execute cowsay
          run: cowsay -f dragon "Run with your dragon" >> dragon.txt
        
        - name: check files and print outout
          run: |
            grep -i "dragon" dragon.txt
            cat dragon.txt
            ls -al
