name: matrix-workflow
on: workflow_dispatch

jobs:
    deploy-on-multiple-os:
        strategy:
          fail-fast: false
          max-parallel: 3
          matrix:
            os: [ubuntu-latest, ubuntu-22.04, windows-latest]
            image: [hello-world, alpine]
            exclude:
              - image: alpine
                os: windows-latest
            include:
              - image: amd64/alpine
                os: ubuntu-20.04
        runs-on: ${{matrix.os}}
        steps:
        - name: Docker info on ${{matrix.os}}
          run: docker info
        - name : Docker run image ${{matrix.image}}
          run: docker run ${{matrix.image}}