name: matrix-workflow
on: workflow_dispatch

jobs:
    deploy-on-multiple-os:
        strategy:
          matrix:
            os: [ubuntu-latest,ubuntu-23.04,windows-latest]
            image: [hello-world]
        runs-on: ${{matrix.os}}
        steps:
        - name: Docker info on ${{matrix.os}}
          run: docker info
        - name : Docker run image ${{matrix.image}}
          run: docker run ${{matrix.image}}