name: workflow-filters

on:
  push:
    branches:
        - main
        - '!feature/*'
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger workflow on event
      run: echo job was triggered bcs of event ${{github.event}}
