name: workflow-filters

on:
  push:
    branches:
        - main
        - '!feature/*'

  pull_request:
    branches:
        - main
    types:
      - opened
      - closed
    paths-ignore:
        - README.md

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger workflow on event
      run: echo job was triggered bcs of event ${{github.event_name}}
